### ISSUE TITLE
Issue when rendering images

### ISSUE THREAD

**Issue by danielvartan** [ropensci-org/rotemplate#54] opened 2021-12-03 18:18 UTC
`rotemplate` is having some issue related to image rendering. The bug is recent.

## Example (today - 2021-12-03)

Source: https://docs.ropensci.org/mctq/

![image](https://user-images.githubusercontent.com/29462472/144651818-f4a0334a-b9da-4d49-93ba-c1e96445dc6f.png)

## Print from 2021-11-10

Source: https://web.archive.org/web/*/https://docs.ropensci.org/mctq/

![image](https://user-images.githubusercontent.com/29462472/144652612-b2c9b5a1-88ec-47bb-a966-bd41582e7e1f.png)

**Comment by jeroen** [comment] 2021-12-03 18:25
Ouch. I think this is due to the new pkgdown? Maelle is working on it in https://github.com/ropensci-org/rotemplate/pull/52

**Comment by Bisaloo** [comment] 2021-12-03 19:12
We had the same problem in https://github.com/epiforecasts/covidregionaldata/issues/441. It is fixed by https://github.com/epiforecasts/covidregionaldata/commit/a19643ff780775a8a3bfc6c4b7813000038fc9af.

**Comment by Bisaloo** [comment] 2021-12-03 19:15
But as mentioned in the issue and as suggested by @jeroen, this will also be fixed by the switch to BS5 (because the logo gets its own class there).

**Comment by jeroen** [comment] 2021-12-03 20:14
The problem is caused by https://github.com/r-lib/pkgdown/pull/1791 (@hadley) which forces the image height to `auto` 

```css
.contents img {
  max-width: 100%;
  height: auto;
}
```

I'll add a workaround to our template until we switch to BS5, though I think the same problem may appear there.

**Comment by jeroen** [comment] 2021-12-05 14:35
I have deployed a hotfix for the old template and rebuilt all ropensci docs.

**Closed as completed by jeroen** 2021-12-05 14:35 UTC
